import Head from 'next/head';

export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>Cryptorank test task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ placeContent: 'center' }}>
        <h1>Home Page</h1>
      </main>
    </>
  );
}
